services:
  - type: web
    name: voicecraft
    env: node
    rootDir: VoiceCraft
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
 
